# Data Transformation

In [1]:
# dependencies
import csv
import json
import pandas as pd
import pymongo

# customisations - ensure tables show all columns
pd.set_option("max_columns", 100)

In [2]:
# Load the app_list data extracted from steamspy API
app_list = pd.read_csv('Data/app_list.csv')
app_list.head()

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,570,Dota 2,Valve,Valve,NaN,1231949,228624,0,"100,000,000 .. 200,000,000",34674,1535,1013,718,0,0,0,509412
1,730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,NaN,4698693,633657,0,"50,000,000 .. 100,000,000",29044,974,8180,407,0,0,0,1030379
2,440,Team Fortress 2,Valve,Valve,NaN,713187,44917,0,"50,000,000 .. 100,000,000",8786,1208,430,362,0,0,0,104499
3,578080,PLAYERUNKNOWN'S BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",NaN,901900,767516,0,"50,000,000 .. 100,000,000",25442,672,11647,245,2999,2999,0,227673
4,304930,Unturned,Smartly Dressed Games,Smartly Dressed Games,NaN,384630,37019,0,"20,000,000 .. 50,000,000",5104,1817,340,840,0,0,0,25080

In [3]:
# Load the app_data data extracted from steamspy API
app_data=pd.read_json('Data/app_data.json')
app_data.head()

,type,name,steam_appid,is_free,developers,publishers,categories,genres,recommendations,release_date,controller_support,achievements,price_overview,ext_user_account_notice,drm_notice
0,game,Dota 2,570,1.0,[Valve],[Valve],"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 14613},"{'coming_soon': False, 'date': '9 Jul, 2013'}",NaN,NaN,NaN,NaN,NaN
1,game,Counter-Strike: Global Offensive,730,1.0,"[Valve, Hidden Path Entertainment]",[Valve],"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 3013382},"{'coming_soon': False, 'date': '21 Aug, 2012'}",full,"{'total': 167, 'highlighted': [{'name': 'Someo...",NaN,NaN,NaN
2,game,Team Fortress 2,440,1.0,[Valve],[Valve],"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 11937},"{'coming_soon': False, 'date': '10 Oct, 2007'}",NaN,"{'total': 520, 'highlighted': [{'name': 'Head ...",NaN,NaN,NaN
3,game,PLAYERUNKNOWN'S BATTLEGROUNDS,578080,0.0,"[KRAFTON, Inc.]","[KRAFTON, Inc.]","[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 1394065},"{'coming_soon': False, 'date': '21 Dec, 2017'}",NaN,"{'total': 37, 'highlighted': [{'name': 'Last S...","{'currency': 'AUD', 'initial': 4295, 'final': ...",NaN,NaN
4,game,Unturned,304930,1.0,[Smartly Dressed Games],[Smartly Dressed Games],"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 7665},"{'coming_soon': False, 'date': '7 Jul, 2017'}",NaN,"{'total': 46, 'highlighted': [{'name': 'Welcom...",NaN,NaN,NaN

### Data Merging

In [4]:
# Rename the app id column for merging
app_data.rename(columns={'steam_appid':'appid'},inplace=True)
app_data.head()

,type,name,appid,is_free,developers,publishers,categories,genres,recommendations,release_date,controller_support,achievements,price_overview,ext_user_account_notice,drm_notice
0,game,Dota 2,570,1.0,[Valve],[Valve],"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 14613},"{'coming_soon': False, 'date': '9 Jul, 2013'}",NaN,NaN,NaN,NaN,NaN
1,game,Counter-Strike: Global Offensive,730,1.0,"[Valve, Hidden Path Entertainment]",[Valve],"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 3013382},"{'coming_soon': False, 'date': '21 Aug, 2012'}",full,"{'total': 167, 'highlighted': [{'name': 'Someo...",NaN,NaN,NaN
2,game,Team Fortress 2,440,1.0,[Valve],[Valve],"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 11937},"{'coming_soon': False, 'date': '10 Oct, 2007'}",NaN,"{'total': 520, 'highlighted': [{'name': 'Head ...",NaN,NaN,NaN
3,game,PLAYERUNKNOWN'S BATTLEGROUNDS,578080,0.0,"[KRAFTON, Inc.]","[KRAFTON, Inc.]","[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 1394065},"{'coming_soon': False, 'date': '21 Dec, 2017'}",NaN,"{'total': 37, 'highlighted': [{'name': 'Last S...","{'currency': 'AUD', 'initial': 4295, 'final': ...",NaN,NaN
4,game,Unturned,304930,1.0,[Smartly Dressed Games],[Smartly Dressed Games],"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 7665},"{'coming_soon': False, 'date': '7 Jul, 2017'}",NaN,"{'total': 46, 'highlighted': [{'name': 'Welcom...",NaN,NaN,NaN

In [5]:
# Merge the two dataframes based on the unique app id
steam_game_df=app_list.merge(app_data,how='inner',on='appid')
steam_game_df.head()

,appid,name_x,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu,type,name_y,is_free,developers,publishers,categories,genres,recommendations,release_date,controller_support,achievements,price_overview,ext_user_account_notice,drm_notice
0,570,Dota 2,Valve,Valve,NaN,1231949,228624,0,"100,000,000 .. 200,000,000",34674,1535,1013,718,0,0,0,509412,game,Dota 2,1.0,[Valve],[Valve],"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 14613},"{'coming_soon': False, 'date': '9 Jul, 2013'}",NaN,NaN,NaN,NaN,NaN
1,730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,NaN,4698693,633657,0,"50,000,000 .. 100,000,000",29044,974,8180,407,0,0,0,1030379,game,Counter-Strike: Global Offensive,1.0,"[Valve, Hidden Path Entertainment]",[Valve],"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 3013382},"{'coming_soon': False, 'date': '21 Aug, 2012'}",full,"{'total': 167, 'highlighted': [{'name': 'Someo...",NaN,NaN,NaN
2,440,Team Fortress 2,Valve,Valve,NaN,713187,44917,0,"50,000,000 .. 100,000,000",8786,1208,430,362,0,0,0,104499,game,Team Fortress 2,1.0,[Valve],[Valve],"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 11937},"{'coming_soon': False, 'date': '10 Oct, 2007'}",NaN,"{'total': 520, 'highlighted': [{'name': 'Head ...",NaN,NaN,NaN
3,578080,PLAYERUNKNOWN'S BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",NaN,901900,767516,0,"50,000,000 .. 100,000,000",25442,672,11647,245,2999,2999,0,227673,game,PLAYERUNKNOWN'S BATTLEGROUNDS,0.0,"[KRAFTON, Inc.]","[KRAFTON, Inc.]","[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 1394065},"{'coming_soon': False, 'date': '21 Dec, 2017'}",NaN,"{'total': 37, 'highlighted': [{'name': 'Last S...","{'currency': 'AUD', 'initial': 4295, 'final': ...",NaN,NaN
4,304930,Unturned,Smartly Dressed Games,Smartly Dressed Games,NaN,384630,37019,0,"20,000,000 .. 50,000,000",5104,1817,340,840,0,0,0,25080,game,Unturned,1.0,[Smartly Dressed Games],[Smartly Dressed Games],"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 7665},"{'coming_soon': False, 'date': '7 Jul, 2017'}",NaN,"{'total': 46, 'highlighted': [{'name': 'Welcom...",NaN,NaN,NaN

### Data selection

In [6]:
# Select the game from the app list
steam_game_df=steam_game_df.loc[steam_game_df['type']=='game']

### Data filtration

In [7]:
# Drop the uesless columns
steam_game_df.drop(columns=['score_rank','userscore','price',
                            'initialprice','discount','name_y',
                            'developers','publishers','controller_support',
                            'achievements','ext_user_account_notice','drm_notice'],inplace=True)

In [8]:
steam_game_df.head()

,appid,name_x,developer,publisher,positive,negative,owners,average_forever,average_2weeks,median_forever,median_2weeks,ccu,type,is_free,categories,genres,recommendations,release_date,price_overview
0,570,Dota 2,Valve,Valve,1231949,228624,"100,000,000 .. 200,000,000",34674,1535,1013,718,509412,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 14613},"{'coming_soon': False, 'date': '9 Jul, 2013'}",NaN
1,730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,4698693,633657,"50,000,000 .. 100,000,000",29044,974,8180,407,1030379,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 3013382},"{'coming_soon': False, 'date': '21 Aug, 2012'}",NaN
2,440,Team Fortress 2,Valve,Valve,713187,44917,"50,000,000 .. 100,000,000",8786,1208,430,362,104499,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 11937},"{'coming_soon': False, 'date': '10 Oct, 2007'}",NaN
3,578080,PLAYERUNKNOWN'S BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",901900,767516,"50,000,000 .. 100,000,000",25442,672,11647,245,227673,game,0.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 1394065},"{'coming_soon': False, 'date': '21 Dec, 2017'}","{'currency': 'AUD', 'initial': 4295, 'final': ..."
4,304930,Unturned,Smartly Dressed Games,Smartly Dressed Games,384630,37019,"20,000,000 .. 50,000,000",5104,1817,340,840,25080,game,1.0,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}, {'id': ...",{'total': 7665},"{'coming_soon': False, 'date': '7 Jul, 2017'}",NaN

### Data Cleaning

In [9]:
# Drop the duplicated games
steam_game_df.drop_duplicates(subset=['appid'],inplace=True)

### Data Spliting

In [10]:
# Spliting the dictionary-type columns
rc_df=steam_game_df['recommendations'].apply(pd.Series)
rd_df=steam_game_df['release_date'].apply(pd.Series)
pc_df=steam_game_df['price_overview'].apply(pd.Series)

In [11]:
# drop the index colums
rc_df=rc_df['total']
rd_df=rd_df[['coming_soon','date']]
pc_df=pc_df[['currency','final','initial']]

### Data aggregating

In [12]:
# Aggregate the data of price/release_data/recommendations togther with previous dataframe
steam_game_df=pd.concat([steam_game_df,rc_df,rd_df,pc_df],axis=1)

In [13]:
# Drop the old unsplitted columns
steam_game_df.drop(columns=['recommendations','release_date','price_overview'],inplace=True)

In [14]:
steam_game_df.head()

,appid,name_x,developer,publisher,positive,negative,owners,average_forever,average_2weeks,median_forever,median_2weeks,ccu,type,is_free,categories,genres,total,coming_soon,date,currency,final,initial
0,570,Dota 2,Valve,Valve,1231949,228624,"100,000,000 .. 200,000,000",34674,1535,1013,718,509412,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",14613.0,False,"9 Jul, 2013",NaN,NaN,NaN
1,730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,4698693,633657,"50,000,000 .. 100,000,000",29044,974,8180,407,1030379,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",3013382.0,False,"21 Aug, 2012",NaN,NaN,NaN
2,440,Team Fortress 2,Valve,Valve,713187,44917,"50,000,000 .. 100,000,000",8786,1208,430,362,104499,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",11937.0,False,"10 Oct, 2007",NaN,NaN,NaN
3,578080,PLAYERUNKNOWN'S BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",901900,767516,"50,000,000 .. 100,000,000",25442,672,11647,245,227673,game,0.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",1394065.0,False,"21 Dec, 2017",AUD,4295.0,4295.0
4,304930,Unturned,Smartly Dressed Games,Smartly Dressed Games,384630,37019,"20,000,000 .. 50,000,000",5104,1817,340,840,25080,game,1.0,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}, {'id': ...",7665.0,False,"7 Jul, 2017",NaN,NaN,NaN

In [15]:
# Rename the column for easier reading
steam_game_df.rename(columns={'name_x':'name',
                              'average_forever':'Avg_playtime_tot',
                             'average_2weeks':'Avg_playtime_2weeks',
                             'median_forever':'Med_playtime_tot',
                             'median_2weeks':'Med_playtime_2weeks',
                              'total':'recommendations',
                             'final':'Final_price',
                             'initial':'Initial_price'},inplace=True)

In [16]:
steam_game_df.head()

,appid,name,developer,publisher,positive,negative,owners,Avg_playtime_tot,Avg_playtime_2weeks,Med_playtime_tot,Med_playtime_2weeks,ccu,type,is_free,categories,genres,recommendations,coming_soon,date,currency,Final_price,Initial_price
0,570,Dota 2,Valve,Valve,1231949,228624,"100,000,000 .. 200,000,000",34674,1535,1013,718,509412,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",14613.0,False,"9 Jul, 2013",NaN,NaN,NaN
1,730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,4698693,633657,"50,000,000 .. 100,000,000",29044,974,8180,407,1030379,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",3013382.0,False,"21 Aug, 2012",NaN,NaN,NaN
2,440,Team Fortress 2,Valve,Valve,713187,44917,"50,000,000 .. 100,000,000",8786,1208,430,362,104499,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",11937.0,False,"10 Oct, 2007",NaN,NaN,NaN
3,578080,PLAYERUNKNOWN'S BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",901900,767516,"50,000,000 .. 100,000,000",25442,672,11647,245,227673,game,0.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",1394065.0,False,"21 Dec, 2017",AUD,4295.0,4295.0
4,304930,Unturned,Smartly Dressed Games,Smartly Dressed Games,384630,37019,"20,000,000 .. 50,000,000",5104,1817,340,840,25080,game,1.0,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}, {'id': ...",7665.0,False,"7 Jul, 2017",NaN,NaN,NaN

### Data filtering and operating

In [17]:
# filtering the null value
steam_game_df=steam_game_df[(steam_game_df['is_free']==1.0) | (steam_game_df.currency.notnull())]

In [18]:
steam_game_df['currency'].fillna(value='AUD',inplace=True)
steam_game_df['Final_price'].fillna(value=0,inplace=True)
steam_game_df['Initial_price'].fillna(value=0,inplace=True)
steam_game_df['recommendations'].fillna(value=0,inplace=True)

In [19]:
# convert the price to reabable value
steam_game_df['Final_price']=steam_game_df['Final_price'].div(100)

In [20]:
# convert the price to reabable value
steam_game_df['Initial_price']=steam_game_df['Initial_price'].div(100)

In [21]:
steam_game_df.dropna(inplace=True)

In [22]:
# reset the index
steam_game_df.reset_index(drop=True, inplace=True)

In [23]:
steam_game_df

,appid,name,developer,publisher,positive,negative,owners,Avg_playtime_tot,Avg_playtime_2weeks,Med_playtime_tot,Med_playtime_2weeks,ccu,type,is_free,categories,genres,recommendations,coming_soon,date,currency,Final_price,Initial_price
0,570,Dota 2,Valve,Valve,1231949,228624,"100,000,000 .. 200,000,000",34674,1535,1013,718,509412,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",14613.0,False,"9 Jul, 2013",AUD,0.00,0.00
1,730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,4698693,633657,"50,000,000 .. 100,000,000",29044,974,8180,407,1030379,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",3013382.0,False,"21 Aug, 2012",AUD,0.00,0.00
2,440,Team Fortress 2,Valve,Valve,713187,44917,"50,000,000 .. 100,000,000",8786,1208,430,362,104499,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",11937.0,False,"10 Oct, 2007",AUD,0.00,0.00
3,578080,PLAYERUNKNOWN'S BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",901900,767516,"50,000,000 .. 100,000,000",25442,672,11647,245,227673,game,0.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",1394065.0,False,"21 Dec, 2017",AUD,42.95,42.95
4,304930,Unturned,Smartly Dressed Games,Smartly Dressed Games,384630,37019,"20,000,000 .. 50,000,000",5104,1817,340,840,25080,game,1.0,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}, {'id': ...",7665.0,False,"7 Jul, 2017",AUD,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8746,38450,MDK,Shiny Entertainment,Interplay Inc.,192,55,"20,000 .. 50,000",1,0,1,0,0,game,0.0,"[{'id': 2, 'description': 'Single-player'}]","[{'id': '1', 'description': 'Action'}]",225.0,False,"17 Sep, 2009",AUD,14.50,14.50
8747,599000,Pizza Connection 2,Assemble Entertainment,Assemble Entertainment,102,40,"20,000 .. 50,000",0,0,0,0,0,game,0.0,"[{'id': 2, 'description': 'Single-player'}]","[{'id': '28', 'description': 'Simulation'}, {'...",116.0,False,"5 Apr, 2017",AUD,8.50,8.50
8748,827780,Margot's Word Brain,Slam Productions Ltd,Funbox Media Ltd,1,3,"20,000 .. 50,000",0,0,0,0,0,game,0.0,"[{'id': 2, 'description': 'Single-player'}]","[{'id': '4', 'description': 'Casual'}, {'id': ...",0.0,False,"5 Apr, 2018",AUD,4.50,4.50
8749,377070,Noctropolis,"Flashpoint Studios, Nightdive Studios",Nightdive Studios,39,7,"20,000 .. 50,000",308,0,308,0,0,game,0.0,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '25', 'description': 'Adventure'}]",0.0,False,"3 Sep, 2015",AUD,14.50,14.50
8750,252050,Construction Machines 2014,GameCask,GameCask,37,275,"20,000 .. 50,000",4,0,4,0,0,game,0.0,"[{'id': 2, 'description': 'Single-player'}]","[{'id': '28', 'description': 'Simulation'}]",239.0,False,"28 Mar, 2014",AUD,9.95,9.95

# Data Load

In [24]:
 # Initialize PyMongo to work with MongoDBs
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

In [25]:
# Define the 'steam_game_database' database in Mongo
db = client["steam_game_database"]

In [26]:
# Drop the game collection if exists
db.games.drop()

In [27]:
# Load the data frame to game collection in database
db.games.insert_many(steam_game_df.to_dict('records'))

# Data read - example

In [28]:
 # Initialize PyMongo to work with MongoDBs
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Read the 'steam_game_database' database in Mongo
read_db = client['steam_game_database']

In [29]:
read_db.collections

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'steam_game_database'), 'collections')

In [30]:
# Read the game collection in Mongo
games = read_db.games

In [31]:
# Import the game collection in Mongo to pandas dataframe
read_game_data = pd.DataFrame(list(games.find()))

In [32]:
read_game_data.head()

,_id,appid,name,developer,publisher,positive,negative,owners,Avg_playtime_tot,Avg_playtime_2weeks,Med_playtime_tot,Med_playtime_2weeks,ccu,type,is_free,categories,genres,recommendations,coming_soon,date,currency,Final_price,Initial_price
0,603b80262df5ccf3ddae136f,570,Dota 2,Valve,Valve,1231949,228624,"100,000,000 .. 200,000,000",34674,1535,1013,718,509412,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",14613.0,False,"9 Jul, 2013",AUD,0.00,0.00
1,603b80262df5ccf3ddae1370,730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,4698693,633657,"50,000,000 .. 100,000,000",29044,974,8180,407,1030379,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",3013382.0,False,"21 Aug, 2012",AUD,0.00,0.00
2,603b80262df5ccf3ddae1371,440,Team Fortress 2,Valve,Valve,713187,44917,"50,000,000 .. 100,000,000",8786,1208,430,362,104499,game,1.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",11937.0,False,"10 Oct, 2007",AUD,0.00,0.00
3,603b80262df5ccf3ddae1372,578080,PLAYERUNKNOWN'S BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",901900,767516,"50,000,000 .. 100,000,000",25442,672,11647,245,227673,game,0.0,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}, {'id': ...",1394065.0,False,"21 Dec, 2017",AUD,42.95,42.95
4,603b80262df5ccf3ddae1373,304930,Unturned,Smartly Dressed Games,Smartly Dressed Games,384630,37019,"20,000,000 .. 50,000,000",5104,1817,340,840,25080,game,1.0,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}, {'id': ...",7665.0,False,"7 Jul, 2017",AUD,0.00,0.00